import type { DayTemplate, ExerciseTemplate } from "./types";

// A full 6-day Push/Pull/Legs split using nothing but bodyweight — for
// training at home without dumbbells, or outdoors in a park. A sturdy
// bench/step/chair is used for two exercises (very common in parks); every
// other movement needs zero equipment. Day numbers/names/subtitles match the
// gym program exactly so per-user day rotation and the dashboard UI work
// unchanged.

function ex(
  overrides: Partial<ExerciseTemplate> &
    Pick<ExerciseTemplate, "slug" | "name" | "equip" | "primary" | "baseSets" | "baseReps" | "baseRest" | "cues" | "mistakes" | "alt" | "tip">,
): ExerciseTemplate {
  return {
    secondary: [],
    baseRpe: "RPE 7–8",
    tempo: "2-1-2",
    difficulty: "beginner",
    breathing: "Exhale on exertion (the lift), inhale on the lowering phase.",
    image: "/images/placeholder-exercise.jpg",
    videoUrl: null,
    ...overrides,
  };
}

const PUSH_WARMUP = [
  "Light cardio (jumping jacks / high knees) — 3 min",
  "Arm circles — 2×15 each way",
  "Shoulder rolls — 2×10",
  "Push-up to downward dog — 1×8",
];
const PUSH_COOLDOWN = [
  "Chest doorway stretch — 30s/side",
  "Overhead triceps stretch — 30s/side",
  "Shoulder cross-body stretch — 30s/side",
  "Child's pose — 45s",
];
const PULL_WARMUP = [
  "Light cardio — 3 min",
  "Arm circles — 2×15 each way",
  "Cat-cow stretch — 1×10",
  "Torso rotations — 1×10 each way",
];
const PULL_COOLDOWN = [
  "Overhead lat stretch — 30s/side",
  "Doorway biceps stretch — 30s/side",
  "Child's pose reach — 45s",
  "Neck & upper-back release — 30s",
];
const LEGS_WARMUP = [
  "Light cardio — 3 min",
  "Bodyweight squats — 2×15",
  "Walking lunges — 1×10 each leg",
  "Leg swings (front-back, side-side) — 1×10 each",
];
const LEGS_COOLDOWN = [
  "Standing quad stretch — 30s/side",
  "Seated hamstring stretch — 30s/side",
  "Calf stretch against a wall — 30s/side",
  "Glute figure-4 stretch — 30s/side",
];

export const BODYWEIGHT_DAY_TEMPLATES: DayTemplate[] = [
  {
    key: "pushA",
    dayNumber: 1,
    name: "Push A",
    subtitle: "Chest, Shoulders, Triceps",
    warmup: PUSH_WARMUP,
    cooldown: PUSH_COOLDOWN,
    exercises: [
      ex({
        slug: "push-up",
        name: "Push-Up",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["triceps", "frontDelts"],
        baseSets: 4,
        baseReps: "10–15",
        baseRest: "90s",
        cues: ["Hands slightly wider than shoulders", "Body in a straight line head to heels", "Lower chest to just above the floor"],
        mistakes: ["Hips sagging or piking up", "Only doing a half range of motion"],
        alt: "Incline Push-Up (hands elevated) if too hard",
        tip: "This is your main chest lift for the day — treat it like a heavy compound, not a warm-up.",
        videoUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
      }),
      ex({
        slug: "decline-push-up",
        name: "Decline Push-Up",
        equip: "Bodyweight + Bench, Step, or Stairs",
        primary: ["chest", "frontDelts"],
        secondary: ["triceps"],
        baseSets: 3,
        baseReps: "8–12",
        difficulty: "moderate",
        baseRest: "90s",
        cues: ["Feet elevated on a bench, step, or stairs", "Hands under shoulders, body straight", "Lower with control, full range"],
        mistakes: ["Elevating feet too high, shifting load to shoulders unsafely", "Sagging hips"],
        alt: "Regular Push-Up",
        tip: "Elevating the feet shifts more work to the upper chest and shoulders.",
      }),
      ex({
        slug: "pike-push-up",
        name: "Pike Push-Up",
        equip: "Bodyweight",
        primary: ["sideDelts", "frontDelts"],
        secondary: ["triceps"],
        baseSets: 3,
        baseReps: "8–12",
        difficulty: "moderate",
        baseRest: "90s",
        cues: ["Hips high, forming an inverted V shape", "Lower your head toward the floor between your hands", "Press back up through the shoulders"],
        mistakes: ["Letting the hips drop toward a regular push-up", "Flaring elbows too wide"],
        alt: "Standing Dumbbell Shoulder Press",
        tip: "The higher your hips, the more this loads the shoulders like an overhead press.",
        videoUrl: "https://www.youtube.com/watch?v=DG-NcMnfZ_0",
      }),
      ex({
        slug: "diamond-push-up",
        name: "Diamond Push-Up",
        equip: "Bodyweight",
        primary: ["triceps"],
        secondary: ["chest", "frontDelts"],
        baseSets: 3,
        baseReps: "8–12",
        difficulty: "moderate",
        baseRest: "75s",
        cues: ["Hands together under your chest, thumbs and index fingers touching", "Elbows track back close to your ribs", "Lower chest to your hands"],
        mistakes: ["Flaring elbows out wide", "Sagging hips"],
        alt: "Regular Push-Up",
        tip: "Drop to your knees to keep good form if the full version breaks down early.",
        videoUrl: "https://www.youtube.com/watch?v=l02EZAm-qn0",
      }),
      ex({
        slug: "tricep-dip-bench",
        name: "Bench/Chair Triceps Dip",
        equip: "Bench, Chair, or Park Bench",
        primary: ["triceps"],
        secondary: ["chest", "frontDelts"],
        baseSets: 3,
        baseReps: "10–15",
        baseRest: "90s",
        cues: ["Hands on the edge, fingers forward, legs extended", "Lower straight down, elbows pointing back", "Press back up without locking out aggressively"],
        mistakes: ["Shoulders shrugging up toward the ears", "Going too deep and straining the shoulder joint"],
        alt: "Diamond Push-Up",
        tip: "Bend your knees and keep feet closer to the bench to make this easier while you build strength.",
        videoUrl: "https://www.youtube.com/watch?v=j_WpuVY3wbo",
      }),
      reuseGymPlank(),
      ex({
        slug: "plank-shoulder-tap",
        name: "Plank Shoulder Tap",
        equip: "Bodyweight",
        primary: ["abs"],
        secondary: ["sideDelts", "obliques"],
        baseSets: 3,
        baseReps: "16–20 (total taps)",
        baseRest: "60s",
        cues: ["High plank position, hands under shoulders", "Tap the opposite shoulder without rotating your hips", "Widen your feet for more stability"],
        mistakes: ["Hips rocking side to side", "Rushing the taps"],
        alt: "Plank",
        tip: "Slower is harder here — the goal is a still, stable torso while your hand moves.",
        videoUrl: "https://www.youtube.com/watch?v=0PrTUpElJ44",
      }),
    ],
  },
  {
    key: "pullA",
    dayNumber: 2,
    name: "Pull A",
    subtitle: "Back, Biceps, Rear Delts",
    warmup: PULL_WARMUP,
    cooldown: PULL_COOLDOWN,
    exercises: [
      ex({
        slug: "table-inverted-row",
        name: "Table/Low-Bar Inverted Row",
        equip: "Sturdy Table or Park Bar",
        primary: ["lats"],
        secondary: ["biceps", "traps"],
        baseSets: 4,
        baseReps: "8–12",
        baseRest: "120s",
        difficulty: "moderate",
        cues: ["Lie under a sturdy table/low bar, grip the edge, body straight", "Pull your chest up toward the table/bar", "Lower with control, arms fully extended"],
        mistakes: ["Using furniture that isn't sturdy enough — test it with weight first", "Sagging hips"],
        alt: "Superman",
        tip: "Walk your feet further away to make it harder, closer in to make it easier — same movement, adjustable difficulty.",
        videoUrl: "https://www.youtube.com/watch?v=Fl0UMfdEzsE",
      }),
      ex({
        slug: "superman",
        name: "Superman",
        equip: "Bodyweight",
        primary: ["lowerBack"],
        secondary: ["glutes"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms extended overhead", "Raise arms, chest, and legs off the floor together", "Squeeze at the top for a beat, then lower"],
        mistakes: ["Yanking upward instead of a controlled lift", "Holding your breath"],
        alt: "Bird Dog",
        tip: "This is a small range of motion — a controlled few inches beats a big jerky lift.",
        videoUrl: "https://www.youtube.com/watch?v=cZxtPxeR2H8",
      }),
      ex({
        slug: "prone-y-raise",
        name: "Prone Y-Raise",
        equip: "Bodyweight",
        primary: ["rearDelts"],
        secondary: ["traps"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms extended overhead in a Y shape", "Lift your arms and chest slightly off the floor", "Squeeze your shoulder blades down and together"],
        mistakes: ["Shrugging the shoulders up toward the ears", "Using the neck to generate the lift"],
        alt: "Dumbbell Reverse Fly",
        tip: "The range of motion is small — this is about the squeeze, not height.",
      }),
      ex({
        slug: "reverse-snow-angel",
        name: "Reverse Snow Angel",
        equip: "Bodyweight",
        primary: ["rearDelts"],
        secondary: ["traps", "lowerBack"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms at your sides, palms down", "Sweep your arms up overhead like a snow angel, lifting them off the floor", "Return with control"],
        mistakes: ["Letting the arms drag/rest on the floor", "Moving too fast to keep the arms lifted"],
        alt: "Prone Y-Raise",
        tip: "Keep a slight lift through the whole arc — that constant tension is what trains the rear delts.",
      }),
      ex({
        slug: "doorframe-isometric-row",
        name: "Doorframe Isometric Row",
        equip: "Doorframe",
        primary: ["lats"],
        secondary: ["biceps", "traps"],
        baseSets: 3,
        baseReps: "20–30s hold each side",
        baseRest: "60s",
        baseRpe: "Hold with good tension",
        cues: ["Grip the inside edge of a doorframe with one hand", "Lean back, pulling against the frame like a row", "Keep your shoulder blade pulled down and back"],
        mistakes: ["Locking the elbow straight (no tension)", "Leaning with a rounded back"],
        alt: "Table Inverted Row",
        tip: "This is an isometric hold — pull hard enough that you genuinely feel the back working.",
        videoUrl: "https://www.youtube.com/watch?v=lfPrQ8jahkM",
      }),
      ex({
        slug: "towel-isometric-curl",
        name: "Towel Isometric Curl",
        equip: "Towel",
        primary: ["biceps"],
        secondary: ["forearms"],
        baseSets: 3,
        baseReps: "20–30s hold each arm",
        baseRest: "60s",
        baseRpe: "Hold with maximum tension",
        cues: ["Stand on one end of a towel, grip the other end", "Curl up while pulling hard against the towel with your foot", "Hold the top position under constant tension"],
        mistakes: ["Not pulling hard enough to create real resistance", "Letting the elbow drift forward"],
        alt: "Dumbbell Curl (if you have dumbbells)",
        tip: "Fatigue builds fast with isometrics — a genuine hard 20 seconds is plenty.",
        videoUrl: "https://www.youtube.com/shorts/XKySx6ADUNQ",
      }),
      ex({
        slug: "bird-dog",
        name: "Bird Dog",
        equip: "Bodyweight",
        primary: ["lowerBack"],
        secondary: ["abs", "glutes"],
        baseSets: 3,
        baseReps: "10–12 each side",
        baseRest: "60s",
        cues: ["Start on hands and knees, spine neutral", "Extend opposite arm and leg out straight", "Keep your hips level — don't let them rotate"],
        mistakes: ["Arching the lower back as the leg lifts", "Rushing through reps without a pause"],
        alt: "Superman",
        tip: "Pause a full second at full extension — that's where the stability work happens.",
        videoUrl: "https://www.youtube.com/watch?v=ZdAHe9_HeEw",
      }),
    ],
  },
  {
    key: "legsA",
    dayNumber: 3,
    name: "Legs A",
    subtitle: "Quads, Hamstrings, Glutes, Calves",
    warmup: LEGS_WARMUP,
    cooldown: LEGS_COOLDOWN,
    exercises: [
      ex({
        slug: "bodyweight-squat",
        name: "Bodyweight Squat",
        equip: "Bodyweight",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings"],
        baseSets: 4,
        baseReps: "15–20",
        baseRest: "90s",
        cues: ["Feet shoulder-width, toes slightly out", "Sit back and down, chest up", "Drive through the whole foot to stand"],
        mistakes: ["Heels lifting off the floor", "Knees caving inward"],
        alt: "Jump Squat (more advanced)",
        tip: "Once 20 clean reps feels easy, add pauses at the bottom or move to jump squats.",
        videoUrl: "https://www.youtube.com/watch?v=cB0cOX7gePg",
      }),
      ex({
        slug: "reverse-lunge",
        name: "Reverse Lunge",
        equip: "Bodyweight",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings"],
        baseSets: 3,
        baseReps: "10–12 each leg",
        baseRest: "90s",
        cues: ["Step one leg back, lower until both knees hit ~90°", "Keep your torso upright", "Push through the front heel to return to standing"],
        mistakes: ["Front knee traveling far past the toes", "Losing balance by stepping too narrow"],
        alt: "Walking Lunge",
        tip: "Stepping backward is easier to balance on than stepping forward — good if lunges feel wobbly.",
        videoUrl: "https://www.youtube.com/watch?v=sb1GbA4Dp04",
      }),
      ex({
        slug: "single-leg-glute-bridge",
        name: "Single-Leg Glute Bridge",
        equip: "Bodyweight",
        primary: ["glutes"],
        secondary: ["hamstrings"],
        baseSets: 3,
        baseReps: "12–15 each side",
        baseRest: "75s",
        cues: ["Lie on your back, one knee bent foot flat, other leg extended", "Drive through the planted heel, squeeze the glute at the top", "Keep your hips level — don't let them tilt"],
        mistakes: ["Hips dropping/rotating toward the lifted leg", "Arching the lower back instead of squeezing glutes"],
        alt: "Two-Leg Glute Bridge",
        tip: "If your hips can't stay level, regress to the two-leg version until you build the strength.",
        videoUrl: "https://www.youtube.com/watch?v=VUl8R0kn6v4",
      }),
      ex({
        slug: "step-up-park-bench",
        name: "Step-Up (Bench or Stairs)",
        equip: "Bench, Step, or Stairs",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings"],
        baseSets: 4,
        baseReps: "10–12 each leg",
        baseRest: "90s",
        cues: ["Full foot planted on the step, not just the toes", "Drive through that foot to stand fully upright", "Step down with control, don't just fall off"],
        mistakes: ["Pushing off the bottom foot to help", "Using a step too high for your current strength"],
        alt: "Reverse Lunge",
        tip: "A park bench is perfect for this — no equipment needed, just a solid step.",
        videoUrl: "https://www.youtube.com/watch?v=vOiHvzj5XhA",
      }),
      ex({
        slug: "wall-sit",
        name: "Wall Sit",
        equip: "Bodyweight",
        primary: ["quads"],
        secondary: [],
        baseSets: 3,
        baseReps: "30–45s hold",
        baseRest: "60s",
        baseRpe: "Hold with good form",
        cues: ["Back flat against a wall, thighs parallel to the floor", "Knees tracking over your ankles, not past your toes", "Breathe steadily throughout the hold"],
        mistakes: ["Sliding too low or too high on the wall", "Holding your breath"],
        alt: "Bodyweight Squat (paused reps)",
        tip: "This burns — that's quad endurance working, not a sign something's wrong.",
        videoUrl: "https://www.youtube.com/watch?v=JaZNYM3zAP0",
      }),
      ex({
        slug: "calf-raise",
        name: "Calf Raise",
        equip: "Bodyweight",
        primary: ["calves"],
        secondary: [],
        baseSets: 4,
        baseReps: "20–25",
        baseRest: "60s",
        cues: ["Stand on a step edge if available for full range", "Rise onto your toes as high as possible", "Pause at the top, lower slowly"],
        mistakes: ["Bouncing through a partial range", "Rushing the lowering phase"],
        alt: "Single-Leg Calf Raise (harder)",
        tip: "Slow and controlled beats fast and bouncy for calf growth every time.",
        videoUrl: "https://www.youtube.com/watch?v=EmyjIRHl3CU",
      }),
      ex({
        slug: "russian-twist-bodyweight",
        name: "Russian Twist",
        equip: "Bodyweight",
        primary: ["obliques", "abs"],
        secondary: [],
        baseSets: 3,
        baseReps: "16–20 (total taps)",
        baseRest: "60s",
        cues: ["Lean back to about 45°, feet lifted if you can", "Rotate side to side, tapping the floor near your hip", "Move from the ribs, not just the arms"],
        mistakes: ["Rounding the back excessively", "Moving too fast to control the rotation"],
        alt: "Bicycle Crunch",
        tip: "Keep feet on the floor if lifting them breaks your form — control matters more than the harder variation.",
        videoUrl: "https://www.youtube.com/watch?v=IJDOoVyVjhc",
      }),
    ],
  },
  {
    key: "pushB",
    dayNumber: 4,
    name: "Push B",
    subtitle: "Chest, Shoulders, Triceps",
    warmup: PUSH_WARMUP,
    cooldown: PUSH_COOLDOWN,
    exercises: [
      ex({
        slug: "wide-push-up",
        name: "Wide Push-Up",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["frontDelts"],
        baseSets: 4,
        baseReps: "10–15",
        baseRest: "90s",
        cues: ["Hands set wider than shoulder width", "Elbows flare slightly more than a regular push-up", "Full range — chest close to the floor"],
        mistakes: ["Going too wide and straining the shoulders", "Partial reps"],
        alt: "Push-Up",
        tip: "A wider hand position emphasizes the outer chest more than a standard push-up.",
        videoUrl: "https://www.youtube.com/watch?v=Va6XjAKEoYE",
      }),
      ex({
        slug: "pike-push-up-elevated",
        name: "Elevated Pike Push-Up",
        equip: "Bodyweight + Bench, Step, or Stairs",
        primary: ["sideDelts", "frontDelts"],
        secondary: ["triceps"],
        baseSets: 3,
        baseReps: "6–10",
        difficulty: "moderate",
        baseRest: "120s",
        cues: ["Feet elevated on a step/bench, hips high in a pike shape", "Lower your head toward the floor between your hands", "Press back up through the shoulders"],
        mistakes: ["Feet too elevated before you're ready, losing form", "Letting the hips drop"],
        alt: "Pike Push-Up (feet on the floor)",
        tip: "This is one of the hardest bodyweight shoulder movements — build up to it with regular pike push-ups first.",
        videoUrl: "https://www.youtube.com/watch?v=8URA3YSur2M",
      }),
      ex({
        slug: "tricep-dip-bench",
        name: "Bench/Chair Triceps Dip",
        equip: "Bench, Chair, or Park Bench",
        primary: ["triceps"],
        secondary: ["chest", "frontDelts"],
        baseSets: 3,
        baseReps: "10–15",
        baseRest: "90s",
        cues: ["Hands on the edge, fingers forward, legs extended", "Lower straight down, elbows pointing back", "Press back up without locking out aggressively"],
        mistakes: ["Shoulders shrugging up toward the ears", "Going too deep and straining the shoulder joint"],
        alt: "Diamond Push-Up",
        tip: "Bend your knees and keep feet closer to the bench to make this easier.",
        videoUrl: "https://www.youtube.com/watch?v=j_WpuVY3wbo",
      }),
      ex({
        slug: "plank-walkout",
        name: "Plank Walkout",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["triceps", "abs"],
        baseSets: 3,
        baseReps: "8–10",
        baseRest: "75s",
        cues: ["Start standing, hinge and walk your hands out to a plank", "Do one push-up (optional) at the bottom", "Walk your hands back to your feet and stand"],
        mistakes: ["Letting the hips sag on the way out", "Bending the knees to cheat the walkout"],
        alt: "Push-Up",
        tip: "Great full-body warm-up-to-work movement that also stretches your hamstrings.",
        videoUrl: "https://www.youtube.com/watch?v=iqVpjKAUETY",
      }),
      ex({
        slug: "archer-push-up",
        name: "Archer Push-Up",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["triceps", "frontDelts"],
        baseSets: 3,
        baseReps: "6–8 each side",
        difficulty: "moderate",
        baseRest: "90s",
        cues: ["Hands set very wide, wider than a wide push-up", "Shift your weight to one side, bending that elbow, other arm stays straight", "Push back to center, alternate sides"],
        mistakes: ["Not shifting weight far enough to load one side properly", "Sagging hips"],
        alt: "Wide Push-Up",
        tip: "This unilaterally loads one arm much harder — great progression toward a one-arm push-up.",
        videoUrl: "https://www.youtube.com/watch?v=L109Ad4zCR4",
      }),
      ex({
        slug: "incline-push-up",
        name: "Incline Push-Up",
        equip: "Bodyweight + Bench, Step, or Wall",
        primary: ["chest"],
        secondary: ["triceps", "frontDelts"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Hands elevated on a bench, step, or wall", "Body in a straight line", "Lower chest to your hands"],
        mistakes: ["Hips sagging", "Using a surface so high there's barely any range of motion"],
        alt: "Regular Push-Up",
        tip: "A good finisher after harder push-up variations — the incline makes it easier to grind out extra reps.",
        videoUrl: "https://www.youtube.com/watch?v=0JUrOH--Kdk",
      }),
      reuseGymPlank(),
    ],
  },
  {
    key: "pullB",
    dayNumber: 5,
    name: "Pull B",
    subtitle: "Back, Biceps, Rear Delts",
    warmup: PULL_WARMUP,
    cooldown: PULL_COOLDOWN,
    exercises: [
      ex({
        slug: "table-inverted-row",
        name: "Table/Low-Bar Inverted Row",
        equip: "Sturdy Table or Park Bar",
        primary: ["lats"],
        secondary: ["biceps", "traps"],
        baseSets: 4,
        baseReps: "8–12",
        baseRest: "120s",
        difficulty: "moderate",
        cues: ["Lie under a sturdy table/low bar, grip the edge, body straight", "Pull your chest up toward the table/bar", "Lower with control, arms fully extended"],
        mistakes: ["Using furniture that isn't sturdy enough — test it with weight first", "Sagging hips"],
        alt: "Doorframe Isometric Row",
        tip: "If you have park access, a low horizontal bar works even better than a table.",
        videoUrl: "https://www.youtube.com/watch?v=Fl0UMfdEzsE",
      }),
      ex({
        slug: "prone-t-raise",
        name: "Prone T-Raise",
        equip: "Bodyweight",
        primary: ["rearDelts"],
        secondary: ["traps"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms extended straight out to the sides (T shape)", "Lift arms and chest slightly off the floor", "Squeeze shoulder blades together at the top"],
        mistakes: ["Shrugging the shoulders up instead of squeezing the blades", "Lifting the neck instead of the chest"],
        alt: "Prone Y-Raise",
        tip: "The T angle emphasizes the rear delts and mid-traps slightly differently than the Y version.",
        videoUrl: "https://www.youtube.com/watch?v=3GJoiYUYwr0",
      }),
      ex({
        slug: "doorframe-isometric-row",
        name: "Doorframe Isometric Row",
        equip: "Doorframe",
        primary: ["lats"],
        secondary: ["biceps", "traps"],
        baseSets: 3,
        baseReps: "20–30s hold each side",
        baseRest: "60s",
        baseRpe: "Hold with good tension",
        cues: ["Grip the inside edge of a doorframe with one hand", "Lean back, pulling against the frame like a row", "Keep your shoulder blade pulled down and back"],
        mistakes: ["Locking the elbow straight (no tension)", "Leaning with a rounded back"],
        alt: "Table Inverted Row",
        tip: "This is an isometric hold — pull hard enough that you genuinely feel the back working.",
        videoUrl: "https://www.youtube.com/watch?v=lfPrQ8jahkM",
      }),
      ex({
        slug: "superman",
        name: "Superman",
        equip: "Bodyweight",
        primary: ["lowerBack"],
        secondary: ["glutes"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms extended overhead", "Raise arms, chest, and legs off the floor together", "Squeeze at the top for a beat, then lower"],
        mistakes: ["Yanking upward instead of a controlled lift", "Holding your breath"],
        alt: "Bird Dog",
        tip: "Same cue as Pull A — quality over height on the lift.",
        videoUrl: "https://www.youtube.com/watch?v=cZxtPxeR2H8",
      }),
      ex({
        slug: "towel-hammer-curl-isometric",
        name: "Towel Isometric Hammer Curl",
        equip: "Towel",
        primary: ["biceps"],
        secondary: ["forearms"],
        baseSets: 3,
        baseReps: "20–30s hold each arm",
        baseRest: "60s",
        baseRpe: "Hold with maximum tension",
        cues: ["Stand on one end of a towel, grip the other end with a neutral (palms-in) grip", "Curl up while pulling hard against the towel with your foot", "Hold under constant tension"],
        mistakes: ["Not creating enough resistance through the foot", "Letting the elbow drift forward"],
        alt: "Towel Isometric Curl",
        tip: "The neutral grip shifts more emphasis onto the forearms and brachialis than a regular curl grip.",
        videoUrl: "https://www.youtube.com/shorts/XKySx6ADUNQ",
      }),
      ex({
        slug: "bird-dog",
        name: "Bird Dog",
        equip: "Bodyweight",
        primary: ["lowerBack"],
        secondary: ["abs", "glutes"],
        baseSets: 3,
        baseReps: "10–12 each side",
        baseRest: "60s",
        cues: ["Start on hands and knees, spine neutral", "Extend opposite arm and leg out straight", "Keep your hips level — don't let them rotate"],
        mistakes: ["Arching the lower back as the leg lifts", "Rushing through reps without a pause"],
        alt: "Superman",
        tip: "Pause a full second at full extension — that's where the stability work happens.",
        videoUrl: "https://www.youtube.com/watch?v=ZdAHe9_HeEw",
      }),
      ex({
        slug: "side-plank",
        name: "Side Plank",
        equip: "Bodyweight",
        primary: ["obliques"],
        secondary: ["abs", "lowerBack"],
        baseSets: 3,
        baseReps: "25–35s hold each side",
        baseRest: "60s",
        baseRpe: "Hold with good form",
        cues: ["Forearm and feet stacked, hips lifted into a straight line", "Don't let your hips sag toward the floor", "Stack your top foot on the bottom, or stagger for balance"],
        mistakes: ["Hips dropping over the course of the hold", "Rotating forward or backward"],
        alt: "Plank",
        tip: "If your hips sag before the target time, that's your real hold time — build up from there.",
        videoUrl: "https://www.youtube.com/watch?v=iNbH7_edNI8",
      }),
    ],
  },
  {
    key: "legsB",
    dayNumber: 6,
    name: "Legs B",
    subtitle: "Quads, Hamstrings, Glutes, Calves",
    warmup: LEGS_WARMUP,
    cooldown: LEGS_COOLDOWN,
    exercises: [
      ex({
        slug: "jump-squat",
        name: "Jump Squat",
        equip: "Bodyweight",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings", "calves"],
        baseSets: 4,
        baseReps: "10–12",
        difficulty: "moderate",
        baseRest: "90s",
        cues: ["Squat down like a normal bodyweight squat", "Explode upward into a jump, arms driving up", "Land softly, straight back into the next squat"],
        mistakes: ["Landing stiff-legged instead of absorbing with a soft knee bend", "Letting the knees cave in on landing"],
        alt: "Bodyweight Squat",
        tip: "Focus on a soft, quiet landing — that's the sign you're absorbing force correctly.",
        videoUrl: "https://www.youtube.com/watch?v=tZSYZdtbONc",
      }),
      ex({
        slug: "curtsy-lunge",
        name: "Curtsy Lunge",
        equip: "Bodyweight",
        primary: ["glutes", "quads"],
        secondary: ["hamstrings"],
        baseSets: 3,
        baseReps: "10–12 each leg",
        baseRest: "90s",
        cues: ["Step one leg diagonally behind the other, like a curtsy", "Lower until both knees bend to about 90°", "Push through the front heel to return to standing"],
        mistakes: ["Rotating the hips instead of keeping them square", "Losing balance by stepping too far"],
        alt: "Reverse Lunge",
        tip: "The diagonal step angle hits the glute medius (side of the hip) more than a straight lunge.",
        videoUrl: "https://www.youtube.com/watch?v=yv0gSJLFhJE",
      }),
      ex({
        slug: "single-leg-romanian-deadlift-bodyweight",
        name: "Single-Leg Romanian Deadlift",
        equip: "Bodyweight",
        primary: ["hamstrings", "glutes"],
        secondary: ["lowerBack"],
        baseSets: 3,
        baseReps: "10–12 each side",
        difficulty: "moderate",
        baseRest: "90s",
        cues: ["Stand on one leg, soft knee bend", "Hinge forward as the free leg extends straight back", "Keep your hips square to the floor, arms out for balance"],
        mistakes: ["Rotating the hips open", "Rounding the lower back"],
        alt: "Two-Leg Glute Bridge",
        tip: "Touch a wall lightly with one hand at first if balance — not strength — is the limiting factor.",
      }),
      ex({
        slug: "glute-bridge-march",
        name: "Glute Bridge March",
        equip: "Bodyweight",
        primary: ["glutes"],
        secondary: ["hamstrings", "abs"],
        baseSets: 3,
        baseReps: "10–12 each leg",
        baseRest: "75s",
        cues: ["Hold a two-leg glute bridge at the top", "Lift one knee toward your chest without dropping your hips", "Place it down and switch legs"],
        mistakes: ["Hips dropping when a leg lifts", "Rushing the leg switch"],
        alt: "Single-Leg Glute Bridge",
        tip: "Keeping the hips level throughout is harder — and more valuable — than the leg lift itself.",
        videoUrl: "https://www.youtube.com/watch?v=MJwQ94J8_pE",
      }),
      ex({
        slug: "single-leg-calf-raise",
        name: "Single-Leg Calf Raise",
        equip: "Bodyweight",
        primary: ["calves"],
        secondary: [],
        baseSets: 3,
        baseReps: "15–20 each side",
        baseRest: "60s",
        cues: ["Stand on one foot, use a wall for light balance support", "Rise onto your toes as high as possible", "Lower slowly, full stretch at the bottom"],
        mistakes: ["Using the wall to push instead of just balance", "Bouncing through partial reps"],
        alt: "Calf Raise (both feet)",
        tip: "Single-leg work exposes and fixes side-to-side calf imbalances.",
        videoUrl: "https://www.youtube.com/watch?v=td7TMmbV8wI",
      }),
      ex({
        slug: "sumo-squat-pulse",
        name: "Sumo Squat Pulse",
        equip: "Bodyweight",
        primary: ["quads", "glutes"],
        secondary: [],
        baseSets: 3,
        baseReps: "20 pulses",
        baseRest: "60s",
        cues: ["Wide stance, sink to the bottom of a sumo squat", "Small pulsing movement, staying low the whole time", "Keep chest up throughout"],
        mistakes: ["Standing up between pulses", "Letting the knees drift inward"],
        alt: "Bodyweight Squat",
        tip: "This is a burnout finisher — expect it to burn, that's the point.",
        videoUrl: "https://www.youtube.com/watch?v=QnZAF0lsS2o",
      }),
      ex({
        slug: "plank-leg-lift",
        name: "Plank Leg Lift",
        equip: "Bodyweight",
        primary: ["abs", "glutes"],
        secondary: ["lowerBack"],
        baseSets: 3,
        baseReps: "10–12 each leg",
        baseRest: "60s",
        cues: ["Hold a standard forearm plank", "Lift one leg a few inches without rotating your hips", "Lower and switch legs"],
        mistakes: ["Letting the hips rotate/twist as the leg lifts", "Hips sagging or piking during the hold"],
        alt: "Plank",
        tip: "If your hips wobble when you lift a leg, that's the sign to keep the lift smaller.",
      }),
    ],
  },
];

function reuseGymPlank(): ExerciseTemplate {
  return {
    slug: "plank",
    name: "Plank",
    equip: "Bodyweight",
    primary: ["abs"],
    secondary: ["obliques", "lowerBack"],
    baseSets: 3,
    baseReps: "30–45s hold",
    baseRest: "45s",
    baseRpe: "Hold with good form",
    tempo: "2-1-2",
    difficulty: "beginner",
    breathing: "Exhale on exertion (the lift), inhale on the lowering phase.",
    cues: ["Neutral spine, ribs down", "Squeeze glutes", "Breathe steadily throughout"],
    mistakes: ["Hips sagging", "Hips piked too high", "Holding your breath"],
    alt: "Dead Bug",
    tip: "Quality over duration — a clean 30s beats a sloppy 60s.",
    image: "/images/plank.jpg",
    videoUrl: null,
  };
}
