import { DAY_TEMPLATES } from "./data";
import type { DayTemplate, ExerciseTemplate } from "./types";

// A full 6-day Push/Pull/Legs split for training at home with just a pair of
// dumbbells (and, for a few exercises, a sturdy chair/sofa as a bench
// substitute). Day numbers/names/subtitles match the gym program exactly so
// the per-user day-rotation logic and dashboard UI work unchanged.

function ex(
  overrides: Partial<ExerciseTemplate> &
    Pick<ExerciseTemplate, "slug" | "name" | "equip" | "primary" | "baseSets" | "baseReps" | "baseRest" | "cues" | "mistakes" | "alt" | "tip">,
): ExerciseTemplate {
  return {
    secondary: [],
    baseRpe: "RPE 7–8",
    tempo: "2-1-2",
    difficulty: "beginner",
    breathing: "Exhale on exertion (the lift), inhale on the lowering phase.",
    // Every photo is named after its slug, so the path is derived rather than
    // repeated on each entry. An explicit `image` in overrides still wins.
    image: `/images/${overrides.slug}.jpg`,
    videoUrl: null,
    ...overrides,
  };
}

// Reuse the exact same exercise (cues, form notes, and real photo) from the
// gym program when the movement is genuinely identical.
function reuseGym(slug: string): ExerciseTemplate {
  for (const day of DAY_TEMPLATES) {
    const found = day.exercises.find((e) => e.slug === slug);
    if (found) return found;
  }
  throw new Error(`Exercise not found in gym data: ${slug}`);
}

const PUSH_WARMUP = [
  "Light cardio (jumping jacks / high knees) — 3 min",
  "Arm circles — 2×15 each way",
  "Shoulder rolls — 2×10",
  "Push-up to downward dog — 1×8",
];
const PUSH_COOLDOWN = [
  "Chest doorway stretch — 30s/side",
  "Overhead triceps stretch — 30s/side",
  "Shoulder cross-body stretch — 30s/side",
  "Child's pose — 45s",
];
const PULL_WARMUP = [
  "Light cardio — 3 min",
  "Arm circles — 2×15 each way",
  "Cat-cow stretch — 1×10",
  "Torso rotations — 1×10 each way",
];
const PULL_COOLDOWN = [
  "Overhead lat stretch — 30s/side",
  "Doorway biceps stretch — 30s/side",
  "Child's pose reach — 45s",
  "Neck & upper-back release — 30s",
];
const LEGS_WARMUP = [
  "Light cardio — 3 min",
  "Bodyweight squats — 2×15",
  "Walking lunges — 1×10 each leg",
  "Leg swings (front-back, side-side) — 1×10 each",
];
const LEGS_COOLDOWN = [
  "Standing quad stretch — 30s/side",
  "Seated hamstring stretch — 30s/side",
  "Calf stretch against a wall — 30s/side",
  "Glute figure-4 stretch — 30s/side",
];

export const HOME_DUMBBELL_DAY_TEMPLATES: DayTemplate[] = [
  {
    key: "pushA",
    dayNumber: 1,
    name: "Push A",
    subtitle: "Chest, Shoulders, Triceps",
    warmup: PUSH_WARMUP,
    cooldown: PUSH_COOLDOWN,
    exercises: [
      ex({
        slug: "dumbbell-floor-press",
        name: "Dumbbell Floor Press",
        equip: "Dumbbells",
        primary: ["chest"],
        secondary: ["triceps", "frontDelts"],
        baseSets: 3,
        baseReps: "8–10",
        baseRest: "120s",
        cues: ["Lie on the floor, knees bent, feet flat", "Lower until your upper arms touch the floor", "Press up and slightly in over your chest"],
        mistakes: ["Bouncing elbows off the floor", "Flaring elbows to 90°"],
        alt: "Push-Up",
        tip: "No bench needed — the floor limits your range so it's shoulder-friendly too.",
        videoUrl: "https://www.youtube.com/watch?v=AqYFvc9t_vU",
      }),
      ex({
        slug: "standing-dumbbell-shoulder-press",
        name: "Standing Dumbbell Shoulder Press",
        equip: "Dumbbells",
        primary: ["sideDelts", "frontDelts"],
        secondary: ["triceps"],
        baseSets: 3,
        baseReps: "8–10",
        baseRest: "90s",
        cues: ["Brace your core, ribs down", "Press straight overhead, not forward", "Lower with control to ear level"],
        mistakes: ["Arching the lower back to press", "Using leg drive to cheat the weight up"],
        alt: "Seated Dumbbell Shoulder Press",
        tip: "Standing recruits your core as a stabilizer — keep glutes and abs tight throughout.",
        videoUrl: "https://www.youtube.com/watch?v=OM23fjJB3-0",
      }),
      reuseGym("dumbbell-lateral-raise"),
      ex({
        slug: "push-up",
        name: "Push-Up",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["triceps", "frontDelts"],
        baseSets: 3,
        baseReps: "10–15",
        baseRest: "90s",
        cues: ["Hands slightly wider than shoulders", "Body in a straight line head to heels", "Lower chest to just above the floor"],
        mistakes: ["Hips sagging or piking up", "Only doing a half range of motion"],
        alt: "Incline Push-Up (hands on a chair) if too hard, Decline Push-Up if too easy",
        tip: "If 10 clean reps is too easy, elevate your feet on a chair for more chest/shoulder load.",
        videoUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
      }),
      ex({
        slug: "dumbbell-floor-fly",
        name: "Dumbbell Floor Fly",
        equip: "Dumbbells",
        primary: ["chest"],
        secondary: [],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "75s",
        cues: ["Slight bend in the elbows, locked in place", "Lower until upper arms touch the floor", "Squeeze your chest together at the top"],
        mistakes: ["Bending/straightening the elbows during the rep", "Using too much weight and losing the stretch"],
        alt: "Cable Machine Chest Fly",
        tip: "This is a stretch-and-squeeze movement, not a heavy lift — go lighter than you think.",
      }),
      reuseGym("overhead-triceps-extension"),
      reuseGym("plank"),
    ],
  },
  {
    key: "pullA",
    dayNumber: 2,
    name: "Pull A",
    subtitle: "Back, Biceps, Rear Delts",
    warmup: PULL_WARMUP,
    cooldown: PULL_COOLDOWN,
    exercises: [
      ex({
        slug: "dumbbell-bent-over-row",
        name: "Dumbbell Bent-Over Row",
        equip: "Dumbbells",
        primary: ["lats", "traps"],
        secondary: ["biceps", "lowerBack"],
        baseSets: 4,
        baseReps: "8–10",
        baseRest: "120s",
        cues: ["Hinge at the hips, flat back, soft knees", "Pull the dumbbells to your lower ribs", "Squeeze your shoulder blades together at the top"],
        mistakes: ["Rounding the lower back", "Using momentum/jerking the weight up"],
        alt: "Single-Arm Dumbbell Row",
        tip: "Keep your neck neutral — look at the floor a few feet ahead, not straight down.",
        videoUrl: "https://www.youtube.com/watch?v=fFmwY2dA2ds",
      }),
      reuseGym("single-arm-dumbbell-row"),
      ex({
        slug: "dumbbell-renegade-row",
        name: "Dumbbell Renegade Row",
        equip: "Dumbbells",
        primary: ["lats"],
        secondary: ["abs", "obliques"],
        baseSets: 3,
        baseReps: "8–10 each side",
        baseRest: "90s",
        cues: ["Plank position, hands on dumbbells, feet wide for stability", "Row one dumbbell up without rotating your hips", "Keep your core braced throughout"],
        mistakes: ["Letting the hips rotate/twist toward the lifting side", "Rushing the tempo"],
        alt: "Single-Arm Dumbbell Row",
        tip: "Widen your stance if you feel unstable — stability comes before load here.",
        videoUrl: "https://www.youtube.com/watch?v=te1rv8hxg-k",
      }),
      reuseGym("machine-dumbbell-rear-delt-fly"),
      reuseGym("hammer-curl"),
      reuseGym("dumbbell-concentration-curl"),
      ex({
        slug: "reverse-crunch",
        name: "Reverse Crunch",
        equip: "Bodyweight",
        primary: ["abs"],
        secondary: ["obliques"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie on your back, knees bent to 90°", "Curl your hips off the floor toward your ribs", "Lower with control, don't let momentum take over"],
        mistakes: ["Swinging the legs instead of curling the hips", "Using the arms to push off the floor"],
        alt: "Hanging Knee Raise (if you have a pull-up bar)",
        tip: "Small, controlled range beats a big swinging rep every time.",
        videoUrl: "https://www.youtube.com/watch?v=yH-oSzE5_g0",
      }),
    ],
  },
  {
    key: "legsA",
    dayNumber: 3,
    name: "Legs A",
    subtitle: "Quads, Hamstrings, Glutes, Calves",
    warmup: LEGS_WARMUP,
    cooldown: LEGS_COOLDOWN,
    exercises: [
      ex({
        slug: "dumbbell-goblet-squat",
        name: "Dumbbell Goblet Squat",
        equip: "Dumbbells",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings"],
        baseSets: 4,
        baseReps: "10–12",
        baseRest: "120s",
        cues: ["Hold one dumbbell vertically at your chest", "Sit back and down between your heels", "Drive through the whole foot to stand"],
        mistakes: ["Heels lifting off the floor", "Knees caving inward"],
        alt: "Barbell Back Squat",
        tip: "Elbows brushing the inside of your knees at the bottom is a good depth check.",
        videoUrl: "https://www.youtube.com/watch?v=gm4ln6PO4rc",
      }),
      ex({
        slug: "dumbbell-romanian-deadlift",
        name: "Dumbbell Romanian Deadlift",
        equip: "Dumbbells",
        primary: ["hamstrings", "glutes"],
        secondary: ["lowerBack"],
        baseSets: 4,
        baseReps: "10–12",
        baseRest: "120s",
        cues: ["Soft knees, push your hips straight back", "Keep the dumbbells close to your shins", "Feel the stretch in your hamstrings, then drive hips forward"],
        mistakes: ["Rounding the lower back", "Squatting the movement instead of hinging"],
        alt: "Barbell Romanian Deadlift",
        tip: "This is a hip-hinge, not a squat — your knees barely bend.",
        videoUrl: "https://www.youtube.com/watch?v=V8Hdl1FiNt4",
      }),
      reuseGym("dumbbell-walking-lunge"),
      reuseGym("dumbbell-step-up"),
      ex({
        slug: "single-leg-dumbbell-deadlift",
        name: "Single-Leg Dumbbell Deadlift",
        equip: "Dumbbells",
        primary: ["hamstrings", "glutes"],
        secondary: ["lowerBack"],
        baseSets: 3,
        baseReps: "8–10 each side",
        baseRest: "90s",
        cues: ["Hold a dumbbell in the opposite hand to your standing leg", "Hinge forward as the free leg extends back", "Keep your hips square to the floor"],
        mistakes: ["Rotating the hips open", "Rushing — this is a balance movement first"],
        alt: "Dumbbell Romanian Deadlift (both feet down)",
        tip: "Touch a wall lightly with one hand at first if balance is the limiting factor, not strength.",
      }),
      ex({
        slug: "standing-dumbbell-calf-raise",
        name: "Standing Dumbbell Calf Raise",
        equip: "Dumbbells",
        primary: ["calves"],
        secondary: [],
        baseSets: 4,
        baseReps: "15–20",
        baseRest: "60s",
        cues: ["Stand on a step edge if available for full range", "Rise onto your toes as high as possible", "Pause a beat at the top, lower slowly"],
        mistakes: ["Bouncing through a partial range", "Rushing the eccentric (lowering) phase"],
        alt: "Standing/Seated Calf Raise Machine",
        tip: "Calves respond well to slow tempo and full stretch — don't rush this one.",
        videoUrl: "https://www.youtube.com/watch?v=wxwY7GXxL4k",
      }),
      ex({
        slug: "dumbbell-russian-twist",
        name: "Dumbbell Russian Twist",
        equip: "Dumbbells",
        primary: ["obliques", "abs"],
        secondary: [],
        baseSets: 3,
        baseReps: "16–20 (total taps)",
        baseRest: "60s",
        cues: ["Lean back to about 45°, feet lifted if you can", "Rotate the dumbbell side to side, tapping the floor", "Move from the ribs, not just the arms"],
        mistakes: ["Rounding the back excessively", "Moving too fast to control the rotation"],
        alt: "Cable Woodchopper",
        tip: "Keep feet on the floor if lifting them makes you lose form — this is a strict core movement, not a race.",
      }),
    ],
  },
  {
    key: "pushB",
    dayNumber: 4,
    name: "Push B",
    subtitle: "Chest, Shoulders, Triceps",
    warmup: PUSH_WARMUP,
    cooldown: PUSH_COOLDOWN,
    exercises: [
      reuseGym("incline-dumbbell-press"),
      reuseGym("standing-dumbbell-arnold-press"),
      ex({
        slug: "diamond-push-up",
        name: "Diamond Push-Up",
        equip: "Bodyweight",
        primary: ["triceps"],
        secondary: ["chest", "frontDelts"],
        baseSets: 3,
        baseReps: "8–12",
        baseRest: "90s",
        difficulty: "moderate",
        cues: ["Hands together under your chest, thumbs and index fingers touching", "Elbows track back close to your ribs", "Lower chest to your hands"],
        mistakes: ["Flaring elbows out wide", "Sagging hips"],
        alt: "Regular Push-Up",
        tip: "Drop to your knees to keep good form if the full version breaks down before your target reps.",
        videoUrl: "https://www.youtube.com/watch?v=l02EZAm-qn0",
      }),
      ex({
        slug: "wide-push-up",
        name: "Wide Push-Up",
        equip: "Bodyweight",
        primary: ["chest"],
        secondary: ["frontDelts"],
        baseSets: 3,
        baseReps: "10–15",
        baseRest: "75s",
        cues: ["Hands set wider than shoulder width", "Elbows flare slightly more than a regular push-up", "Full range — chest close to the floor"],
        mistakes: ["Going too wide and straining the shoulders", "Partial reps"],
        alt: "Cable Crossover",
        tip: "A wider hand position emphasizes the outer chest more than a standard push-up.",
        videoUrl: "https://www.youtube.com/watch?v=Va6XjAKEoYE",
      }),
      ex({
        slug: "dumbbell-front-raise",
        name: "Dumbbell Front Raise",
        equip: "Dumbbells",
        primary: ["frontDelts"],
        secondary: [],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Slight bend in the elbows", "Raise to shoulder height, no higher", "Lower with control — don't swing"],
        mistakes: ["Using momentum/body swing to lift", "Raising past shoulder height and shrugging"],
        alt: "Cable Front Raise",
        tip: "Go lighter than you expect — front delts fatigue quickly on isolation work.",
        videoUrl: "https://www.youtube.com/watch?v=BYnam1bnp18",
      }),
      reuseGym("skull-crusher"),
      reuseGym("plank"),
    ],
  },
  {
    key: "pullB",
    dayNumber: 5,
    name: "Pull B",
    subtitle: "Back, Biceps, Rear Delts",
    warmup: PULL_WARMUP,
    cooldown: PULL_COOLDOWN,
    exercises: [
      ex({
        slug: "dumbbell-pullover",
        name: "Dumbbell Pullover",
        equip: "Dumbbells",
        primary: ["lats"],
        secondary: ["chest", "triceps"],
        baseSets: 3,
        baseReps: "10–12",
        baseRest: "90s",
        cues: ["Lie across a chair/sofa with hips supported, or flat on the floor", "Lower the dumbbell back behind your head with slight elbow bend", "Pull it back over your chest, feeling the lats stretch"],
        mistakes: ["Bending the elbows too much (turns it into a triceps move)", "Arching the lower back excessively"],
        alt: "Lat Pulldown",
        tip: "Think of it as pulling from your lats, not pressing from your arms.",
      }),
      reuseGym("chest-supported-dumbbell-row"),
      ex({
        slug: "dumbbell-reverse-fly",
        name: "Dumbbell Reverse Fly",
        equip: "Dumbbells",
        primary: ["rearDelts"],
        secondary: ["traps"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "75s",
        cues: ["Hinge forward at the hips, flat back, dumbbells hanging straight down", "Raise arms out to the sides, squeezing shoulder blades", "Lower with control"],
        mistakes: ["Standing too upright and turning it into a shrug", "Using momentum to swing the weight up"],
        alt: "Cable Face Pull",
        tip: "Lead with your elbows, not your hands, to keep tension on the rear delts.",
        videoUrl: "https://www.youtube.com/watch?v=d1QEddtoOq0",
      }),
      ex({
        slug: "dumbbell-zottman-curl",
        name: "Dumbbell Zottman Curl",
        equip: "Dumbbells",
        primary: ["biceps"],
        secondary: ["forearms"],
        baseSets: 3,
        baseReps: "8–10",
        baseRest: "75s",
        cues: ["Curl up with palms facing up (regular curl)", "Rotate your wrists so palms face down at the top", "Lower slowly with palms down, then rotate back up"],
        mistakes: ["Rushing the wrist rotation", "Swinging the elbows forward"],
        alt: "Standard Dumbbell Curl",
        tip: "The slow palms-down lowering phase is what builds serious forearm strength — don't skip it.",
      }),
      ex({
        slug: "cross-body-hammer-curl",
        name: "Cross-Body Hammer Curl",
        equip: "Dumbbells",
        primary: ["biceps"],
        secondary: ["forearms"],
        baseSets: 3,
        baseReps: "10–12 each arm",
        baseRest: "60s",
        cues: ["Palms face each other (neutral grip)", "Curl the dumbbell across toward the opposite shoulder", "Lower with control back to your side"],
        mistakes: ["Swinging the shoulder forward", "Curling too fast to feel the squeeze"],
        alt: "Hammer Curl",
        tip: "The angled path hits the brachialis slightly differently than a straight hammer curl.",
        videoUrl: "https://www.youtube.com/watch?v=0jLf1MYSp3c",
      }),
      ex({
        slug: "superman",
        name: "Superman",
        equip: "Bodyweight",
        primary: ["lowerBack"],
        secondary: ["glutes"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "60s",
        cues: ["Lie face down, arms extended overhead", "Raise arms, chest, and legs off the floor together", "Squeeze at the top for a beat, then lower"],
        mistakes: ["Yanking upward instead of a controlled lift", "Holding your breath"],
        alt: "Bird Dog",
        tip: "This is a small range of motion — a controlled few inches beats a big, jerky lift.",
        videoUrl: "https://www.youtube.com/watch?v=cZxtPxeR2H8",
      }),
      ex({
        slug: "bicycle-crunch",
        name: "Bicycle Crunch",
        equip: "Bodyweight",
        primary: ["abs"],
        secondary: ["obliques"],
        baseSets: 3,
        baseReps: "16–20 (total taps)",
        baseRest: "60s",
        cues: ["Hands lightly behind your head, elbows wide", "Bring opposite elbow to opposite knee", "Extend the other leg out straight, low to the floor"],
        mistakes: ["Pulling on the neck with your hands", "Going too fast and losing the twist"],
        alt: "Bicycle Crunch",
        tip: "Slow this one down — speed usually means you're using momentum, not your abs.",
        videoUrl: "https://www.youtube.com/watch?v=wpRI3xBhJmo",
      }),
    ],
  },
  {
    key: "legsB",
    dayNumber: 6,
    name: "Legs B",
    subtitle: "Quads, Hamstrings, Glutes, Calves",
    warmup: LEGS_WARMUP,
    cooldown: LEGS_COOLDOWN,
    exercises: [
      ex({
        slug: "dumbbell-sumo-squat",
        name: "Dumbbell Sumo Squat",
        equip: "Dumbbells",
        primary: ["quads", "glutes"],
        secondary: ["hamstrings"],
        baseSets: 4,
        baseReps: "10–12",
        baseRest: "120s",
        cues: ["Wide stance, toes turned out ~30°", "Hold one dumbbell with both hands between your legs", "Sit straight down, chest up"],
        mistakes: ["Knees caving inward", "Leaning too far forward"],
        alt: "Dumbbell Goblet Squat",
        tip: "The wider stance shifts more emphasis onto glutes and inner thighs.",
        videoUrl: "https://www.youtube.com/watch?v=Sq88Uw0roVU",
      }),
      ex({
        slug: "dumbbell-hip-thrust",
        name: "Dumbbell Hip Thrust",
        equip: "Dumbbells + Sofa or Chair",
        primary: ["glutes"],
        secondary: ["hamstrings"],
        baseSets: 4,
        baseReps: "10–12",
        baseRest: "120s",
        cues: ["Upper back braced against a sofa/sturdy chair edge", "Dumbbell resting on your hips", "Drive hips up until your body forms a straight line, squeeze glutes hard"],
        mistakes: ["Overextending the lower back at the top", "Pushing through the toes instead of the heels"],
        alt: "Barbell Hip Thrust",
        tip: "Chin tucked, eyes forward at the top — looking up encourages lower-back overextension.",
      }),
      reuseGym("bulgarian-split-squat"),
      ex({
        slug: "single-leg-dumbbell-calf-raise",
        name: "Single-Leg Dumbbell Calf Raise",
        equip: "Dumbbells",
        primary: ["calves"],
        secondary: [],
        baseSets: 3,
        baseReps: "12–15 each side",
        baseRest: "60s",
        cues: ["Hold one dumbbell, use a wall for light balance support", "Rise onto your toes on one foot", "Lower slowly, full stretch at the bottom"],
        mistakes: ["Using the wall to push instead of just balance", "Bouncing through partial reps"],
        alt: "Standing Dumbbell Calf Raise (both feet)",
        tip: "Single-leg work exposes and fixes side-to-side calf imbalances.",
      }),
      ex({
        slug: "dumbbell-glute-bridge",
        name: "Dumbbell Glute Bridge",
        equip: "Dumbbells",
        primary: ["glutes"],
        secondary: ["hamstrings"],
        baseSets: 3,
        baseReps: "12–15",
        baseRest: "75s",
        cues: ["Lie on your back, knees bent, dumbbell resting on your hips", "Drive through your heels, squeeze glutes at the top", "Lower with control"],
        mistakes: ["Arching the lower back instead of squeezing glutes", "Feet placed too far from the hips"],
        alt: "Dumbbell Hip Thrust",
        tip: "Heels should be close enough to your glutes that your shins are close to vertical at the top.",
        videoUrl: "https://www.youtube.com/watch?v=E6VLOEz7tWE",
      }),
      ex({
        slug: "sumo-squat-pulse",
        name: "Sumo Squat Pulse",
        equip: "Bodyweight",
        primary: ["quads", "glutes"],
        secondary: [],
        baseSets: 3,
        baseReps: "20 pulses",
        baseRest: "60s",
        cues: ["Wide stance, sink to the bottom of a sumo squat", "Small pulsing movement, staying low the whole time", "Keep chest up throughout"],
        mistakes: ["Standing up between pulses", "Letting the knees drift inward"],
        alt: "Dumbbell Sumo Squat",
        tip: "This is a burnout finisher — expect it to burn, that's the point.",
        videoUrl: "https://www.youtube.com/watch?v=QnZAF0lsS2o",
      }),
      ex({
        slug: "plank-leg-lift",
        name: "Plank Leg Lift",
        equip: "Bodyweight",
        primary: ["abs", "glutes"],
        secondary: ["lowerBack"],
        baseSets: 3,
        baseReps: "10–12 each leg",
        baseRest: "60s",
        cues: ["Hold a standard forearm plank", "Lift one leg a few inches without rotating your hips", "Lower and switch legs"],
        mistakes: ["Letting the hips rotate/twist as the leg lifts", "Hips sagging or piking during the hold"],
        alt: "Plank",
        tip: "If your hips wobble when you lift a leg, that's the sign to keep the lift smaller.",
      }),
    ],
  },
];
